stages: ["build", "deploy", "publish", "test"]

building:
  stage: build
  script:
    - yarn
    - yarn run docs:build
  artifacts:
    expire_in: 3 days
    paths:
      - dist
  only:
    - master
  tags:
    - tzedu-hd2-prod-gitrunner01

pages:
  stage: deploy
  script:
    - mkdir public
    - mv dist/* public
  artifacts:
    expire_in: 3 days
    paths:
      - public
  only:
    - master
  tags:
    - tzedu-hd2-prod-gitrunner01

publish:
  stage: publish
  script:
    - git checkout -B "$CI_COMMIT_REF_NAME" "$CI_COMMIT_SHA"
    - yarn
    - yarn run bootstrap
    - git config --global --get user.name
    - git config --global --get user.email
    - echo "http://gitlab-ci-token:$GITLAB_USER_TOKEN@git.tanzk.cn/$CI_PROJECT_PATH.git"
    - git config --global user.name "dashixiong"
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git remote set-url --push origin "http://gitlab-ci-token:$GITLAB_USER_TOKEN@git.tanzk.cn/$CI_PROJECT_PATH.git"
    - git checkout .
    - yarn run build
    - yarn run publish
  only:
    - master
  tags:
    - tzedu-hd2-prod-gitrunner01

test:
  stage: test
  script:
    - yarn run test:cicd
  only:
    - tags
  tags:
    - tzedu-hd2-prod-gitrunner01
